### PR TITLE
Chosen

### PR DESCRIPTION
**Pull request by harrislapiroff**

### CODE REVIEW

**Comment by nmorduch** [comment]
Is there a reason you kept in the chosen files that we do not need? If yes, fine to merge. If no, delete them and then fine to merge.

**Comment by harrislapiroff** [comment]
I find it better not to modify dependencies at all when including them in a project. That way, when debugging, we know with certainty that we have all of the files and also when we upgrade to the next version of chosen, we know we can just swap out the whole directory. I try to think of client side packages the same way I think of third-party python packages. Unless I'm forking and modifying it to add more features, I would never delete python code from, for example, grappelli, just because I wasn't using it.

**Comment by harrislapiroff** [comment]
That having been said, the client side dependency system is kind of a mess. I'd love to use something like bower, if I only liked it.

**Comment by nmorduch** [comment]
But like, the html files that explain the project seem unnecessary.

**Pull request merged**
