### PR TITLE
Added some layouts.

### PR DESCRIPTION
**Pull request by harrislapiroff**
I like columns and panels.

### CODE REVIEW

**Comment by melinath** [comment]
who do you want to review this?

**Comment by harrislapiroff** [comment]
I assigned it to @nmorduch since I think she has the most opinions about templates, but either way, really. If you're itching to have it merged, it can be you.

**Comment by nmorduch** [comment]
I am not merging this because I think that for the group detail page, the way I had it makes a lot of sense for narrower screens. The info you moved to the sidebar takes up little space in my design, and is above the log (which I expect will get tall with use). The sidebar layout puts that information at the bottom for narrower screens, which doesn't make sense to me because you want to have the member list available at the top of the screen for assessing who owes what (and maybe percentages on categories).

For wider screens, I think the sidebar makes sense (though like obviously those lists need styling) but for narrower screens I think we should stick with the existing design. I would also put the logout button in the header, maybe to the right of the settings cog. Which should probably be "Settings" instead of a cog, now that I think about it.

**Comment by harrislapiroff** [comment]
I feel pretty strongly that more than 90% of the time a visitor visits this page what they will want to do is drop in a transaction and be done with it, so the transaction add buttons need to be the number one thing on the page. Other stuff needs to be second, tiny, tucked under a menu, or on another page. Seeing who owes how much is an occasional task. Adding transactions is a constant task.

At least in my houses, people have added transactions constantly to our spreadsheets, but only one person checked once monthly (or less) how much was owed so we could pay off our balances.

**Comment by harrislapiroff** [comment]
That might've come off a little more aggressive than I meant. You're in charge of the design for this project, so I'll defer to your judgment, but give some thought to my reasons.

**Comment by nmorduch** [comment]
Hm that's true but I also don't want that stuff to be at the bottom because there's likely to be a lot of stuff to scroll through to get there, and it needs to be immediately findable. Also whenever I put in transactions I glance at how we're doing so I have a sense of if it's someone else's turn to front the money for groceries — Mirrorhenge, the original user of my spreadsheet, tried to make it mostly just come out even by taking turns paying for things. Also I don't record house transactions in the same place as the rest of my spending except when I settle up, so I like to know all the time if I'm more than like $20 up or down.

So the end result of this is that it should always be easy to see the status of the things, but it should not get in the way of having the primary function be transaction input. However, right now I want to focus on functionality more than on where this stuff is, so we can just merge this for now and deal with this more specifically later.

I am thinking that I would like this to be up and running on the real internet as soon as we are sure that we are not going to be making non-migrable changes to the backend. And then we can do UI with real user input. And my UI priorities lie with the form things, which have much more impact on one's experience, I think.

**Pull request merged**
