### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by harrislapiroff**
This should get us started on styling things.

### CODE REVIEW

**Comment by melinath** [comment]
I really don't like the pattern of having our sass included in our static files... I know it doesn't really _matter_, but is there a compelling reason _not_ to just put the sass folder in argus/?

**Comment by harrislapiroff** [comment]
I generally agree with you—it doesn't make sense for instance, for our SASS files to get uploaded to S3 and/or be publicly accessible. But, I also feel pretty uncomfortable separating related files so distantly. It already makes me uncomfortable having `config.rb`, for instance, in the root. If I were new and coming to this project I would have no idea where to start editing CSS files or what that file meant. Is there some solution to that? Some method that keeps everything organized in an intuitive fashion but also doesn't serve our source files?

**Comment by harrislapiroff** [comment]
I guess conceptually it's the difference between having a Django project with a Compass project embedded within it and having a Django project and a Compass project all noodled up together.

**Comment by nmorduch** [comment]
I would consider having both a static folder and like a static-source folder, or something like that. There are also other things we sometimes have hanging out in static, like psd files, which for sure shouldn't be there.

**Comment by melinath** [comment]
I usually do this layout:

```
django-argus
|- argus/
| | - compass.rb
| | - sass/
| | | - styles.scss
| | - static/
| | | - argus/
| | | | - css/
| | | | | - styles.css
```

**Comment by nmorduch** [comment]
I do think I'd rather have it inside something with the same structure as the static folder.

**Comment by melinath** [comment]
@nmorduch So... you like the structure I proposed?

**Comment by harrislapiroff** [comment]
I'm gonna go ahead and implement your proposed structure @melinath. I've got some misgivings, but maybe we can see how it works and change it later.

What's your reasoning for putting `compass.rb` in `/argus/` instead of `/`? Seems like it cleans up the root directory, but adds an extra `cd` step for doing static file development which seems arbitrary.

**Comment by harrislapiroff** [comment]
Actually, I'm starting to see Naomi's point. It might be better to have it mirror the `static/` directory more strictly, i.e.,

```
django-argus
└┬ argus
 ├─ compass.rb
 ├┬ sass/
 │└┬ argus/
 │ └┬ styles/
 │  └─ styles.sass
 └┬ static/
  └┬ argus/
   └┬ styles/
    └─ styles.css
```

(P.S. my folder diagrams look way better without GitHub line spacing.)

which would leave us the option of adding, for instance, an `admin/` subdirectory to static. Otherwise, how would we do that? On the other hand, there's no way to include javascript or images in the structure that I've outlined above.

How have you generally handled this, Stephen? I've generally had separate Compass projects for each subdirectory of `static/` but it seems like that's not compatible with keeping Compass files outside of `static/`.

**Comment by harrislapiroff** [comment]
Sorry, that's a bunch of questions at once. Let me distill them:
1. What's the reasoning for putting `compass.rb` inside `argus/` instead of in the repo root?
2. How can this Compass structure support multiple subdirectories of `argus/static/`?

(I'm willing to defer these questions until they actually cause problems, though, if you want to just go ahead and merge this so we can start working on the styles more iteratively.)

**Comment by melinath** [comment]
No particular reasoning for putting compass.rb inside argus/ instead of in root. I guess root would maybe even make more sense, since it's not really "part" of the package in the same way the templates and static files are.

I don't usually plan on having multiple sass-generated files, since I expect everything to be in a single file anyway. If we do want to have multiple projects, I think your mirrored directory structure would be enough to allow it.

So new dir structure proposal:

```
django-argus
├ compass.rb
├┬ sass/
│└┬ argus/
│ └┬ styles/
│  └─ styles.sass
└┬ argus
 └┬ static/
  └┬ argus/
   └┬ styles/
    └─ styles.css
```

**Comment by harrislapiroff** [comment]
Do you not generally have separate static files for any admin customization?

The trouble with my proposal is that we then need to put images and javascript files in `static/` which means it will be a directory that contains both files which are managed by Compass and files which are manually added, which causes me some discomfort.

**Comment by harrislapiroff** [comment]
Oh, also, I hadn't meant to move the entire `sass/` directory to the outside of the app. Just `compass.rb`. (Which actually can't be called `compass.rb`, I don't think. It has to be `config.rb`.) Though, again, I'm suddenly uncertain of my reasoning.

**Comment by melinath** [comment]
I know you weren't suggesting that the entire `sass` dir be moved... that was my addition. :-)

I don't usually do admin customization, but you're right - that's a thing. And you're right that it would be weird to have non-compass-managed files in a compass-managed dir. Blargh! I don't know any more! :-p

**Comment by melinath** [comment]
I think maybe something like this:

```
django-argus
├ admin.rb
├ argus.rb
├┬ sass/
│├┬ admin/
││└─ styles.sass
│└┬ argus/
│ └─ styles.sass
└┬ argus
 └┬ static/
  ├┬ argus/
  │└┬ styles/
  │ └─ styles.css
  └┬ admin/
   └┬ styles/
    └─ styles.css
```

Then `compass watch -c admin.rb` vs. `compass watch -c argus.rb`.

**Comment by harrislapiroff** [comment]
Something about that still irks me. It precludes `admin/styles.sass` from sharing _any_ SASS content with `argus/styles.sass`. I'd like to keep thinking about this issue, but request that you pull this branch as-is for now—since most of these issues are theoretical at this point—unless you have strong objections to the current state.

**Comment by harrislapiroff** [comment]
(To clarify, I want you, @melinath, to be the one to merge it because I wrote it and I want to be sure all our code is known to two people and I don't think @nmorduch has enough understanding yet of project structure to give this a sufficient review.)

**Comment by melinath** [comment]
- newlines need to be added to a few files.
- Gemfile.lock needs to be taken out of .gitignore (sorry!)

Otherwise looks good!

**Pull request merged**
